SELECT * FROM customer_behaviour;

-- Q1. Which category generates highest revenue?
select  category,
ROUND(sum(purchase_amount_usd)::numeric, 2) as total_revenue
from customer_behaviour
group by category
order by 2 desc ;

-- Business Problem
-- : — Company does not know which category contributes nost to revenue.

-- Impact
         -- Helps prioritize categories
         -- Optimizes inventory planning
         -- Improves marketing ROI



-- Q2. Are discounts actually increasing purchase value?

SELECT 
    discount_applied,
    ROUND(SUM(purchase_amount_usd)::numeric, 2) AS total_revenue,
	ROUND(AVG(purchase_amount_usd)::numeric, 2) AS avg_revenue
FROM customer_behaviour
GROUP BY discount_applied;

-- Business Problem 
--Discounts nay reduce profit •ithout increasing sales.

-- impact
           -- Identify effectiveness Of discounts
           -- Reduce unnecessary discount costs
           -- Inprove profit


-- 3. What is the total revenue generated by male and female customer ?

select 
gender ,
ROUND(SUM(purchase_amount_usd)::numeric, 2) AS total_revenue
from customer_behaviour
group by gender 
order by 2 desc

-- ? Business Problem Lack of understanding of revenue contribution by gender segments 

-- Impact : —
--           -helps design target market campaign
--           —Improves custoner segmentation strategy
--           —Enhances personalization efforts




-- Q4 Which customers use a discount but still spend more than the average purchase amount?

select 
customer_id,
purchase_amount_usd
from customer_behaviour
where discount_applied = 'Yes' and purchase_amount_usd >  (select avg(purchase_amount_usd) from customer_behaviour)
order by 2 desc limit 10 ;

-- Business Problem: The company cannot identify high-spending customers who are also sensitive to discounts

-- Impact: Identifying these "premium discount-sensitive"
          -- customers allows for specialized targeted campaigns that improve
          -- customer retention and maximize revenue from high-value shoppers



-- Q5 Which are the top and bottom five products based on average review rating?

select 
item_purchased,
round(avg(review_rating)::numeric,2) as avg_rating
from customer_behaviour
group by 1
order by 2 asc limit 5;

select 
item_purchased,
round(avg(review_rating)::numeric,2) as avg_rating
from customer_behaviour
group by 1
order by 2 desc limit 5;



(
SELECT 
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS avg_rating,
    'Bottom 5' AS type
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY avg_rating ASC
LIMIT 5
)

UNION ALL

(
SELECT 
    item_purchased,
    ROUND(AVG(review_rating)::numeric, 2) AS avg_rating,
    'Top 5' AS type
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5
);
-- Business Problem: There is no visibility into which specific products are performing best or worst according to customer feedback
-- .
-- Impact: This allows the company to promote high-performing products and 
-- identify low-rated items that require quality improvements to enhance the overall customer experience





-- Q6 Does fast shipping lead to higher spending? (Standard vs. Express)

SELECT 
    shipping_type,
    ROUND(sum(purchase_amount_usd)::numeric, 2) AS total_order_value
FROM customer_behaviour
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;

-- Business Problem: It is unclear if offering faster shipping options actually encourages customers to spend more
.
-- Impact: Insights here help optimize shipping pricing strategies, potentially 
-- increasing the promotion of premium shipping options to boost the average order value
.



-- Q7 Do subscribed customers spend more than non-subscribers?

SELECT 
    subscription_status,
    ROUND(sum(purchase_amount_usd)::numeric, 2) AS total_order_value
FROM customer_behaviour
GROUP BY subscription_status
order by 2 desc;


-- Business Problem: The actual effectiveness and ROI of the loyalty/subscription program are unknown
-- .
-- Impact: This analysis validates the performance of the subscription model, 
-- helping the company decide whether to modify the program to better increase customer lifetime value




-- Q8 Which are the top five products with the highest discount usage?

select 
item_purchased,
count(discount_applied = 'Yes') as times_discount_used
from customer_behaviour
group by item_purchased
order by 2 desc limit 5;

-- Business Problem: Certain products might be overly dependent on discounts, 
-- meaning customers may only buy them when the price is reduced
-- .
-- Impact: Identifying discount-driven products helps the company optimize pricing strategies 
-- and reduce profit margin losses caused by excessive discounting




-- Q9 What is the count of each customer segment (New, Returning, Loyal)?

SELECT 
    CASE 
        WHEN frequency_of_purchases IN ('Weekly', 'Bi-Weekly', 'Fortnightly') THEN 'Loyal'
        WHEN frequency_of_purchases = 'Monthly' THEN 'Returning'
        WHEN frequency_of_purchases IN ('Quarterly', 'Annually', 'Every 3 Months') THEN 'New'
    END AS customer_segment,
    
    COUNT(*) AS total_customers

FROM customer_behaviour
GROUP BY customer_segment
ORDER BY total_customers DESC;


-- Business Problem: A lack of customer segmentation leads to generic, inefficient marketing strategies
-- .
-- Impact: Segmentation enables personalized marketing, allowing the company 
-- to apply different retention strategies for "Loyal" vs. "New" customers, ultimately increasing conversion rates
.



-- Q10 What are the top three most purchased products within each category?


(
SELECT 
    'Clothing' AS category,
    item_purchased,
    COUNT(*) AS times_purchased
FROM customer_behaviour
WHERE category = 'Clothing'
GROUP BY item_purchased
ORDER BY times_purchased DESC
LIMIT 3
)

UNION ALL

(
SELECT 
    'Footwear' AS category,
    item_purchased,
    COUNT(*) AS times_purchased
FROM customer_behaviour
WHERE category = 'Footwear'
GROUP BY item_purchased
ORDER BY times_purchased DESC
LIMIT 3
)

UNION ALL

(
SELECT 
    'Accessories' AS category,
    item_purchased,
    COUNT(*) AS times_purchased
FROM customer_behaviour
WHERE category = 'Accessories'
GROUP BY item_purchased
ORDER BY times_purchased DESC
LIMIT 3
);

-- Business Problem: The company does not know which specific items are the top performers within individual categories
-- .
-- Impact: This helps with inventory optimization (ensuring best-sellers are always in stock)
-- and improves product placement and recommendation algorithms
.




-- Q11 Are repeat buyers (more than five purchases) likely to subscribe?

SELECT 
    subscription_status,
    COUNT(*) AS total_customers,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2 ) AS percentage
FROM customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Business Problem: The relationship between customer loyalty (repeat purchases) and 
-- the adoption of the subscription plan is unclear
-- .
-- Impact: This helps improve subscription targeting by identifying why even loyal customers might not be subscribing, 
-- leading to better-tailored conversion campaigns
.





-- Q12 What is the revenue contribution of each age group?

SELECT 
    CASE 
        WHEN age BETWEEN 18 AND 25 THEN '18-25'
        WHEN age BETWEEN 26 AND 35 THEN '26-35'
        WHEN age BETWEEN 36 AND 50 THEN '36-50'
        ELSE '50+'
    END AS age_group,

    ROUND(SUM(purchase_amount_usd)::numeric, 2) AS total_revenue,

    ROUND(
        (
            SUM(purchase_amount_usd) * 100.0 
            / SUM(SUM(purchase_amount_usd)) OVER ()
        )::numeric,
        2
    ) AS revenue_percentage

FROM customer_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;


-- Business Problem: There is no visibility into which demographic age group generates the most revenue
-- .
-- Impact: This provides the visibility needed to execute age-based targeting 
-- enhances the overall efficiency of marketing campaigns by focusing on the most profitable age brackets
.


-- exporting data 

COPY customer_behaviour
TO 'C:\Users\pk778\Downloads\Customerr Behaviour Analysis\data.csv'
DELIMITER ','
CSV HEADER;






















		 